deployment:
  tasks:
    - export DEPLOYPATH=${HOME}/public_html/OpenTeamsTest
    - echo "Deployment started."
    
    # Step 1: Pull latest changes from the repository
    - /usr/bin/git pull
    
    # Step 2: Install dependencies if needed (e.g., for a Node.js project)
    # Uncomment and modify the following lines as per your project's requirements
    #- cd ${DEPLOYPATH}
    #- /opt/cpanel/ea-nodejs16/bin/npm install
    
    # Step 3: Build the project if required (e.g., for a React/Vue/Angular project)
    # Uncomment and modify the following lines as per your project's requirements
    #- /opt/cpanel/ea-nodejs16/bin/npm run build
    
    # Step 4: Copy files to the deployment directory
    - rsync -av --delete ${HOME}/OpenTeamsTest/ ${DEPLOYPATH}/
    
    - echo "Deployment completed."