---
deployment:
  tasks:
    - export REPOPATH=${HOME}/public_html/OpenTeamsTest
    - echo "Deployment started."

    # Step 1: Navigate to the repository path
    - cd ${REPOPATH}
    
    # Step 2: Add changes to the git staging area
    - /usr/bin/git add .

    # Step 3: Commit changes with a message
    - /usr/bin/git commit -m "Automated commit via cPanel deployment"

    # Step 4: Push changes back to the origin repository
    - /usr/bin/git push origin main

    - echo "Deployment completed."